### ISSUE TITLE
[1.10.2] Crash confined to log regarding updated Forge and update notifications

### ISSUE THREAD

**Issue by b0bst3r** [GenDeathrow/MPUtils#1]
Forge 12.18.2.2099
MPutils 1.10.2-1.2.0
MPbasic 1.10.2-1.1.0

This does not stop the game from loading or working as I think it relates to your update notification code.  I pulled it from the startup log.

http://pastebin.ubuntu.com/23340274/

**Comment by GenDeathrow** [comment]
What does the version number inside mpinfo look like?

**Comment by b0bst3r** [comment]
"version": "1.40"

**Comment by GenDeathrow** [comment]
Ahh thats why..  it looks for x.x.x. not  x.x I will add in a check to just assume it has the third number. 

so 1.40.0 will work. for now

**Comment by GenDeathrow** [comment]
@b0bst3r  this is fixed in the latest version for 1.10.2. I now have a catch for  make sure the version numbers are formatted correctly. If it cant get one of the version numbers it reverts to a 0.  I will prolly add support for _alpha and _beta at some point as well. but atm. its 0.0.0 pattern. Thanks for bringing this to my attention.
